name: downloadable-artifact

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    steps:
      - uses: actions/checkout@master
      - run: mkdir -p ./artifact
      - run: echo hello > ./artifact/world.txt
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
